name: AI Code Review (Claude via Bedrock, OIDC)

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches: [ "**" ]
    paths:
      - '**/*.php'
      - '**/*.js'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.py'
      - '**/*.jsx'
      - '**/*.scss'
      - '**/*.css'
      - '**/*.mustache'
      - '**/*.html'
      - '**/*.md'
      - '!**/*.min.js'
      - '!**/*.map'
      - '!**/*.{png,jpg,jpeg,gif,svg,webp,mp4,mp3,woff,woff2}'

permissions:
  contents: read
  pull-requests: write
  id-token: write  

jobs:
  ai_review:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::701308052646:role/GitHubBedrockReviewer
          aws-region: us-west-2

      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install boto3 requests

      - name: Run Claude review
        id: review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          AWS_REGION: us-west-2
          ANTHROPIC_MODEL_ID: anthropic.claude-3-sonnet-20240229-v1:0          
          MAX_TOKENS: "4000"
        run: |
          python .github/scripts/ai_code_review.py --emit-verdict > verdict.txt
          echo "result=$(cat verdict.txt)" >> $GITHUB_OUTPUT